Vagrant.configure(2) do |config|
	config.vm.box = "generic/centos8"
	config.vm.synced_folder "./app_folder", "/home/vagrant/app_folder", create: true
	config.vm.provision "shell", privileged: true, inline: "systemctl disable firewalld --now"

	config.vm.define "fdidelotS" do |cfg|
		cfg.vm.hostname = "fdidelotS"
		cfg.vm.network "private_network", ip: "192.168.56.110"
		cfg.vm.provider "virtualbox" do |vb|
			vb.name = "fdidelotS"
			vb.memory = 1024
			vb.cpus = 1
		end
		cfg.vm.provision "shell", inline:<<-SHELL
		curl -sfL https://get.k3s.io | sh -s - \
		--write-kubeconfig-mode=644 \
		--flannel-iface=eth1
		/usr/local/bin/k3s kubectl create configmap app-one-configmap --from-file=/home/vagrant/app_folder/app1/index.html
		/usr/local/bin/k3s kubectl create configmap app-two-configmap --from-file=/home/vagrant/app_folder/app2/index.html
		/usr/local/bin/k3s kubectl create configmap app-three-configmap --from-file=/home/vagrant/app_folder/app3/index.html
		/usr/local/bin/k3s kubectl apply -f /home/vagrant/app_folder/app1/
		/usr/local/bin/k3s kubectl apply -f /home/vagrant/app_folder/app2/
		/usr/local/bin/k3s kubectl apply -f /home/vagrant/app_folder/app3/
		SHELL
	end
end